apiVersion: aiven.io/v1alpha1
kind: OpenSearch
metadata:
  name: os-cloudnative
spec:
  # gets the authentication token from the `aiven-token` Secret
  authSecretRef:
    name: aiven-token
    key: token

  # outputs the OpenSearch connection on the `os-secret` Secret
  connInfoSecretTarget:
    name: os-cloudnative

  # add your Project name here
  project: dev-advocates

  # cloud provider and plan of your choice
  # you can check all of the possibilities here https://aiven.io/pricing
  cloudName: google-europe-west1
  plan: startup-4




